global:
  message: Welcome to customer service dev enevironment!!
server:
  port: 8082
message: Hello from Dev!
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cust_dev
    username: root
    password: Subranth@2010
  jpa:
    hiberante:
      ddl-auto: update
    show-sql: true
      
