global:
  message: Welcome to order service dev enevironment!!
server:
  port: 8084
message: Hello from Dev!
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_dev
    username: root
    password: Subranth@2010
  jpa:
    hiberante:
      ddl-auto: update
    show-sql: true
      
