global:
  message: Welcome to order service prod environment!!
server:
  port: 8085
message: Hello from Prod!
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_prod
    username: root
    password: Subranth@2010
  jpa:
    hiberante:
      ddl-auto: update
    show-sql: true
      
